# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b317bd78136e7c8e67fc709c70bed9ca1d6cb512defbb185f4b44f8f08d0f318419b7f876e083b458e0e962a40b7de0cc60f67504e9535c936e55b9cf3283db

test:
  secret_key_base: 010108ff357c03bec77d1e7c250825a8d4993226f15a94dd3163f5a86fe0b5029e3cbf37ca5a6fafdcedca7a1f14242181271f918ef97e571c041368a8df999b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
